els-ASAP auto commit file/tag shared-mime-info-1.8-3.el7.src.rpm

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -1,6 +1,6 @@
 SUBDIRS=. po
 
-INCLUDES = $(ALL_CFLAGS)
+AM_CPPFLAGS = $(ALL_CFLAGS)
 
 packagesdir = $(datadir)/mime/packages
 packages_DATA = freedesktop.org.xml
@@ -89,9 +89,9 @@ if CROSS_COMPILING
 	@echo "Cross compiling: Skipping checks"
 else
 	@if ! test -d staging-tests/ ; then \
-		echo "***********************************************************************" ; \
+		echo "***************************************************************************" ; \
 		echo "*** Add your file to process to staging-tests/ and run local-test again ***" ; \
-		echo "***********************************************************************" ; \
+		echo "***************************************************************************" ; \
 		exit 1 ; \
 	fi
 	if test -d .git/ && test -x ../xdgmime/src/print-mime-data$(EXEEXT) ; then \
@@ -115,13 +115,20 @@ else
 	if test -d .git/ && test -x $(top_builddir)/update-mime-database$(EXEEXT) && test -d $(top_srcdir)/mime-db-tests ; then \
 		$(top_builddir)/update-mime-database$(EXEEXT) mime-db-tests/ ; \
 	fi
-	if test -d .git/ && test -x ../xdgmime/src/test-mime-data$(EXEEXT) && test -x $(top_builddir)/test-tree-magic$(EXEEXT) ; then \
-		mkdir -p $(top_builddir)/temp-mime-dir/mime/packages ; \
-		cp -a $(top_builddir)/freedesktop.org.xml $(top_builddir)/temp-mime-dir/mime/packages/ ; \
-		XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" $(top_builddir)/update-mime-database$(EXEEXT) "$(top_builddir)/temp-mime-dir/mime/" ; \
-		XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" XDG_DATA_HOME="$(top_builddir)/temp-mime-dir/" ../xdgmime/src/test-mime-data$(EXEEXT) -v tests/list || XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" XDG_DATA_HOME="$(top_builddir)/temp-mime-dir/" ../xdgmime/src/test-mime$(EXEEXT) || (XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" ../xdgmime/src/test-mime-data$(EXEEXT) -v -v tests/list ; exit 1); \
-		XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" $(top_builddir)/test-tree-magic$(EXEEXT) tests/tree-list || exit 1; \
-		rm -rf "$(top_builddir)/temp-mime-dir/" ; \
+	@if test -d .git/ ; then \
+		if test ! -x ../xdgmime/src/test-mime-data$(EXEEXT) || test ! -x $(top_builddir)/test-tree-magic$(EXEEXT) ; then \
+			echo "***************************************************************************" ; \
+			echo "*** xdgmime not compiled, test suite cannot run. Check HACKING for info ***" ; \
+			echo "***************************************************************************" ; \
+			exit 1 ; \
+		else \
+			mkdir -p $(top_builddir)/temp-mime-dir/mime/packages ; \
+			cp -a $(top_builddir)/freedesktop.org.xml $(top_builddir)/temp-mime-dir/mime/packages/ ; \
+			XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" $(top_builddir)/update-mime-database$(EXEEXT) "$(top_builddir)/temp-mime-dir/mime/" ; \
+			XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" XDG_DATA_HOME="$(top_builddir)/temp-mime-dir/" ../xdgmime/src/test-mime-data$(EXEEXT) -v tests/list || XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" XDG_DATA_HOME="$(top_builddir)/temp-mime-dir/" ../xdgmime/src/test-mime$(EXEEXT) || (XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" ../xdgmime/src/test-mime-data$(EXEEXT) -v -v tests/list ; exit 1); \
+			XDG_DATA_DIRS="$(top_builddir)/temp-mime-dir/" $(top_builddir)/test-tree-magic$(EXEEXT) tests/tree-list || exit 1; \
+			rm -rf "$(top_builddir)/temp-mime-dir/" ; \
+		fi; \
 	fi
 	@if `grep comment $(srcdir)/freedesktop.org.xml.in | grep -v _comment | grep -q -v '<!'` ; then \
 		echo "***************************************************************************" ; \
@@ -134,12 +141,13 @@ else
 endif
 
 check-translations:
-	@for i in $(top_srcdir)/po/*.po ; do								\
+	@export RET=0 ; for i in $(top_srcdir)/po/*.po ; do						\
 		if ! grep -q ^`basename $$i | sed 's,.po,,'`$$ $(top_srcdir)/po/LINGUAS ; then		\
 			echo '***' `basename $$i | sed 's,.po,,'` missing from po/LINGUAS '***' ;	\
-			exit 1;										\
+			RET=1;										\
 		fi;											\
-	done;
+	done;												\
+	if [ $$RET == 1 ] ; then exit 1; fi
 
 update-translations: create-pot
 	@tx pull --all --force --skip
